---
title: Overspecification--level 1 aggregation
output: html_document
---

Preliminaries

```{r}
rm(list=ls())
library(ggplot2)
library(plyr)
library(bootstrap)
library(lme4)

theme_set(theme_bw()) # ggplot2 theme

#statistics for boolean factors; copied from useful.R, with a slightly different mean function to work with the choiceCorrect factor
l.mean <- function(...){mean(as.logical(...))}
l.theta <- function(x,xdata,na.rm=T) {l.mean(xdata[x],na.rm=na.rm)}
l.ci.low <- function(x,na.rm=T) {
  l.mean(x,na.rm=na.rm) - quantile(bootstrap(1:length(x),1000,l.theta,x,na.rm=na.rm)$thetastar,.025,na.rm=na.rm)}
l.ci.high <- function(x,na.rm=T) {
  quantile(bootstrap(1:length(x),1000,l.theta,x,na.rm=na.rm)$thetastar,.975,na.rm=na.rm) - l.mean(x,na.rm=na.rm)}

```
##Data preprocessing

Load all csv files.

```{r}

d1 <- read.csv("pragmods_overspec_baseline.results.csv")
d1$type <- "text"
d2 <- read.csv("pragmods_overspec_checkbox.results.csv")
d2$type <- "checkbox"
d3 <- read.csv("pragmods_overspec_virtual.results.csv")
d3$type <- "virtual keyboard"

d <- rbind.fill(d1,d2,d3)
d$type <- factor(d$type,
                      levels=c("checkbox","text","virtual keyboard"))
```

Then, exclude the relevant cases from each of them:

```{r}
exclude <- d$Answer.overspec == "NA" | d$Answer.name_check_correct == "\"FALSE\"" 
sum(exclude,na.rm=TRUE)
d <- subset(d, exclude == FALSE)
```

Aggregate: 

```{r}
ms <- ddply(d, .(Answer.features_in_referent_to_describe,type), 
            summarise,
            m = l.mean(Answer.overspec),
            cil = l.ci.low(Answer.overspec),
            cih = l.ci.high(Answer.overspec),
            n = length(Answer.overspec))
```

Visualization
---

Convert the data (with error bars) into a bar graph:

```{r}
quartz()
qplot(Answer.features_in_referent_to_describe, m,
       data=ms,
       geom="bar",
       stat="identity",
       position="dodge",
       fill=type,
       xlab="Features in Referent",
       ylab="Proportion of Overspecification") +
       geom_errorbar(aes(ymin=m - cil, ymax = m + cih), width=0.2, position=position_dodge(width=.9)) +
       ylim(c(0,1)) +
       scale_fill_discrete(name="Experiment Type")
```


Stats
-----

```{r}
d$type <- factor(d$type, levels=c("text","checkbox","virtual keyboard"))
d$features <- factor(d$Answer.features_in_referent_to_describe)
d$ambiguity <- revalue(d$features, 
                       c("0" = "unambig",
                         "1" = "ambig",
                         "2" = "unambig"))


  
summary(glmer(Answer.overspec ~ ambiguity * type + 
                (1|workerid), 
      data=d, family="binomial"))
```
